//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_WEBAPP001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVO()
        {
            this.DETALLESOLICITUD = new HashSet<DETALLESOLICITUD>();
        }
    
        public int IDE_ACT { get; set; }
        public string DES_ACT { get; set; }
        public Nullable<int> IDE_MAR { get; set; }
        public Nullable<int> IDE_CAT { get; set; }
        public int STO_PRO { get; set; }
        public byte[] IMG_PRO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual MARCAS MARCAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLESOLICITUD> DETALLESOLICITUD { get; set; }
    }
}
