//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_WEBAPP001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOLICITUD()
        {
            this.DETALLESOLICITUD = new HashSet<DETALLESOLICITUD>();
        }
    
        public int NUM_SOL { get; set; }
        public System.DateTime FEC_SOL { get; set; }
        public Nullable<int> IDE_TRA { get; set; }
        public string EST_SOL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLESOLICITUD> DETALLESOLICITUD { get; set; }
        public virtual TRABAJADOR TRABAJADOR { get; set; }
    }
}
