//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJ_WEBAPP001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRABAJADOR()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public int IDE_TRA { get; set; }
        public string NOM_TRA { get; set; }
        public string APE_TRA { get; set; }
        public string DIR_TRA { get; set; }
        public string TEL_TRA { get; set; }
        public Nullable<int> IDE_DIS { get; set; }
        public string COR_TRA { get; set; }
        public byte[] IMG_VEN { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
